# Generated by Django 3.2.8 on 2021-10-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('deadline', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
