# Generated by Django 3.2.8 on 2021-11-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ['pk'], 'verbose_name': 'Лабораторная', 'verbose_name_plural': 'Лабораторные'},
        ),
        migrations.RemoveField(
            model_name='lab',
            name='is_published',
        ),
        migrations.AddField(
            model_name='lab',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Выдана'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='deadline',
            field=models.DateField(verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='task',
            field=models.TextField(blank=True, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='UserLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsersLabs', to='labs.lab', verbose_name='Лабораторная студента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyLabs', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
    ]
