# Generated by Django 3.2.8 on 2021-11-27 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0002_auto_20211127_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlab',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Зачтена'),
        ),
        migrations.AddField(
            model_name='userlab',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлена'),
        ),
        migrations.AddField(
            model_name='userlab',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ментор'),
        ),
        migrations.AddField(
            model_name='userlab',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='userlab',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsersLabs', to='labs.lab', verbose_name='Лабораторная'),
        ),
    ]
