# Generated by Django 3.2.8 on 2021-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20211127_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlab',
            name='commits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
