# Generated by Django 3.2.8 on 2021-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_userlab_commits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
