# Generated by Django 3.2.9 on 2021-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальна'),
        ),
    ]
