# Generated by Django 3.2.8 on 2021-12-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_material_is_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_important', models.BooleanField(default=True, verbose_name='Важное')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуально')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['pk'],
            },
        ),
    ]
